# https://cloud.google.com/vpc-service-controls/docs/ingress-egress-rules#ingress-rules-reference
- ingressFrom:
    # ANY_IDENTITY | ANY_USER_ACCOUNT | ANY_SERVICE_ACCOUNT
    # identityType: ANY_IDENTITY
    # *OR*
    identities:
    - serviceAccount:service-[YOUR_PROJECT_NUMBER]@gcp-sa-aiplatform-cc.iam.gserviceaccount.com
    - serviceAccount:service-[YOUR_PROJECT_NUMBER]@gcp-sa-aiplatform.iam.gserviceaccount.com
    - serviceAccount:[YOUR_PROJECT_NUMBER]-compute@developer.gserviceaccount.com
    - user:[YOUR_USER_EMAIL]  # Replace with your email
    sources:
    # - resource: projects/project
    # *OR*
    - accessLevel: "*"
  ingressTo:
    operations:
    - serviceName: storage.googleapis.com
      methodSelectors:
      - method: "*"
    - serviceName: bigquery.googleapis.com
      methodSelectors:
      - method: "*"
    - serviceName: aiplatform.googleapis.com
      methodSelectors:
      - method: "*"
    - serviceName: dns.googleapis.com
      methodSelectors:
      - method: "*"
    - serviceName: artifactregistry.googleapis.com
      methodSelectors:
      - method: "*"
    resources:
    - projects/[YOUR_PROJECT_NUMBER]